namespace T.VT;

/// <summary>
/// Column width of a code point in the terminal grid (0, 1 or 2), following glibc's
/// <c>wcwidth()</c> so the terminal agrees with the programs that position the cursor.
/// The tables are generated by <c>tools/generate-unicode-width.py</c>.
/// </summary>
public static partial class UnicodeWidth
{
    // Widths of the Basic Multilingual Plane, built once from the range tables: O(1) lookup
    // for the characters that actually show up in terminals (Latin, CJK, symbols).
    private static readonly byte[] BmpWidths = BuildBmpTable();

    /// <summary>Returns 0 (combining / zero width), 1 (normal) or 2 (wide) for a Unicode scalar value.</summary>
    public static int GetWidth(int codePoint)
    {
        if ((uint)codePoint < 0x10000)
            return BmpWidths[codePoint];
        if (codePoint > 0x10FFFF)
            return 1;
        if (InRanges(WideRanges, (uint)codePoint))
            return 2;
        return InRanges(ZeroWidthRanges, (uint)codePoint) ? 0 : 1;
    }

    private static byte[] BuildBmpTable()
    {
        var table = new byte[0x10000];
        Array.Fill(table, (byte)1);
        Fill(table, ZeroWidthRanges, 0);
        Fill(table, WideRanges, 2);
        return table;
    }

    private static void Fill(byte[] table, ReadOnlySpan<uint> ranges, byte width)
    {
        for (int i = 0; i < ranges.Length; i += 2)
        {
            if (ranges[i] > 0xFFFF) break;
            uint end = Math.Min(ranges[i + 1], 0xFFFF);
            for (uint cp = ranges[i]; cp <= end; cp++) table[cp] = width;
        }
    }

    private static bool InRanges(ReadOnlySpan<uint> ranges, uint codePoint)
    {
        int lo = 0, hi = (ranges.Length / 2) - 1;
        while (lo <= hi)
        {
            int mid = (lo + hi) >> 1;
            if (codePoint < ranges[mid * 2]) hi = mid - 1;
            else if (codePoint > ranges[(mid * 2) + 1]) lo = mid + 1;
            else return true;
        }
        return false;
    }
}
