"""
Generates T.Terminal/UnicodeWidth.Tables.g.cs from the Unicode database of the running Python.

The rules follow glibc's wcwidth(), which is what most remote programs (bash, vim, tmux, less)
use to lay out text - the terminal must agree with them or the cursor drifts:

  width 0: combining marks (Mn, Me), format characters (Cf, except U+00AD SOFT HYPHEN),
           Hangul Jungseong/Jongseong (U+1160-U+11FF, U+D7B0-U+D7FF)
  width 2: East Asian Wide/Fullwidth (this includes emoji with emoji presentation)
           plus the CJK Unified Ideographs planes 2 and 3
  width 1: everything else

Usage:  python tools/generate-unicode-width.py
"""

import os
import sys
import unicodedata


def width(cp: int) -> int:
    if 0xD800 <= cp <= 0xDFFF:
        return 1
    ch = chr(cp)
    category = unicodedata.category(ch)
    if cp == 0x00AD:
        return 1
    if category in ("Mn", "Me", "Cf"):
        return 0
    if 0x1160 <= cp <= 0x11FF or 0xD7B0 <= cp <= 0xD7FF:
        return 0
    if unicodedata.east_asian_width(ch) in ("W", "F"):
        return 2
    if 0x20000 <= cp <= 0x2FFFD or 0x30000 <= cp <= 0x3FFFD:
        return 2
    return 1


def ranges(target: int):
    result = []
    start = None
    for cp in range(0x110000):
        if width(cp) == target:
            if start is None:
                start = cp
        elif start is not None:
            result.append((start, cp - 1))
            start = None
    if start is not None:
        result.append((start, 0x10FFFF))
    return result


def emit(name: str, items) -> str:
    lines = [f"    internal static ReadOnlySpan<uint> {name} =>", "    ["]
    row = []
    for start, end in items:
        row.append(f"0x{start:05X}, 0x{end:05X}")
        if len(row) == 4:
            lines.append("        " + ", ".join(row) + ",")
            row = []
    if row:
        lines.append("        " + ", ".join(row) + ",")
    lines.append("    ];")
    return "\n".join(lines)


def main():
    root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    target = os.path.join(root, "T.Terminal", "UnicodeWidth.Tables.g.cs")
    zero = ranges(0)
    wide = ranges(2)
    text = "\n".join([
        "// <auto-generated>",
        f"// Generated by tools/generate-unicode-width.py from Unicode {unicodedata.unidata_version}"
        f" (Python {sys.version_info.major}.{sys.version_info.minor}). Do not edit.",
        "// </auto-generated>",
        "",
        "namespace T.VT;",
        "",
        "public static partial class UnicodeWidth",
        "{",
        f"    /// <summary>Unicode version the tables were generated from.</summary>",
        f"    public const string UnicodeVersion = \"{unicodedata.unidata_version}\";",
        "",
        "    // Inclusive [start, end] code point ranges, sorted.",
        emit("ZeroWidthRanges", zero),
        "",
        emit("WideRanges", wide),
        "}",
        "",
    ])
    with open(target, "w", encoding="utf-8", newline="\n") as f:
        f.write(text)
    print(f"{target}: {len(zero)} zero-width ranges, {len(wide)} wide ranges (Unicode {unicodedata.unidata_version})")


if __name__ == "__main__":
    main()
